# Generated by Django 2.2.5 on 2019-09-21 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drive_type', models.CharField(choices=[('googledrive', 'Google Drive'), ('onedrive', 'One Drive'), ('dropbox', 'DropBox'), ('box', 'box'), ('evernote', 'EverNote')], max_length=30)),
                ('file_type', models.CharField(choices=[('directory', 'Directory'), ('file', 'File')], max_length=30)),
                ('file_id', models.CharField(max_length=1000)),
                ('file_name', models.CharField(max_length=1000)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('sync_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
