# Generated by Django 2.2.5 on 2019-09-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_drive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('credential_file', models.FileField(upload_to='')),
            ],
        ),
    ]
