# Generated by Django 2.2.5 on 2019-09-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_drive', '0002_googledrivecredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledrivecredentials',
            name='credential_file',
            field=models.FileField(upload_to='Credentials/'),
        ),
    ]
