# Generated by Django 2.2.5 on 2019-09-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_drive', '0003_auto_20190913_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_credential_file',
            field=models.FileField(blank=True, null=True, upload_to='GoogleDriveCredentials/'),
        ),
    ]
