# Generated by Django 2.2.5 on 2019-09-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_drive', '0005_user_drpdox_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='drpdox_access_token',
            new_name='dropbox_access_token',
        ),
    ]
