# Generated by Django 2.2.5 on 2019-09-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_drive', '0006_auto_20190919_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='box_access_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
