# Generated by Django 2.2.5 on 2019-09-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_drive', '0007_user_box_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onedrive_access_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
